apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.10.0
    helm:
      releaseName: loki
      values: |
        loki:
          auth_enabled: false
        singleBinary:
          replicas: 1
        monitoring:
          selfMonitoring:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
