apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 62.6.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
        prometheus:
          prometheusSpec:
            retention: 15d
            enableRemoteWriteReceiver: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
