apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-api
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
    - apps
  selector:
    matchLabels:
      app: platform-api
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
