apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-healer-controller-manager
  namespace: self-healer-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: self-healer-manager-role
rules:
- apiGroups: ["platform.example.com"]
  resources: ["healingpolicies", "healingpolicies/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "list", "watch", "delete", "create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: self-healer-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-healer-manager-role
subjects:
- kind: ServiceAccount
  name: self-healer-controller-manager
  namespace: self-healer-system
